language: node_js
node_js:
- '4'
notifications:
  email: false
branches:
  except:
  - gh-pages
after_success:
- if [ $TRAVIS_TAG ]; then make deploy; fi
env:
  global:
    secure: ybbxxM4fxJtQAZvzaY7DGRcDHghGFHU4TzpnFFGOYz5x1QbYAtxNf7Qm8zABB1/Fw6BQ0+vighQLUx7HswzEf0xuK6x8lKMpqxiPwCL61lCl1x6Hm94mSNNDtkC3ojBm/bOrlr6kOCfNOh25BsIGIvEKu1zMpeJ8E5RR8MyvuC/x1J6rJ3tktOD8uMCH48CHqZ9eWIX3iSgePKiI6B6HjVA5I0DJ/66hQnCVULsKU9+FB+2CxFUf0TaKOUDo2x1PXnSOsAVN7qPQzYiW6ORXGtsPDqyWIcGgRsQ5dPSNjyA/eAVi8WXOMjgeYLwYiqvNT7IA+lNQ4Uvq3XxVwOzF0mObSnQbdJgwIA3qGi38Ez98oncjKWUgi5frpYR3tDGUVoESttdqwwdu2LdYtxn1TFbahMMYth6ELVsnUlxMBHvoJKXmgALJgJGErwyjOGSIYP/BIhwJM9fYjOgpl/+WjHoS5DSeT0F4mxDUPCQNsBs32swXcwdMCb+KZtQnvg+npIAYxgpbrLGB+f41Yvsv/Z6DhvDVJZ8+ekfe9QyJl+dwVK5CrzrxxI3/lMxnVTGVlFIWWKzsPlpanhCz3/nstTHcZnNTbVoS9RGiYD6VVeLyMdi0DHGmy+L/vOnZ+K78cvOMgNi9oEv5Anh7lqGYH1uHxptHzJX1SNqJw8GNAro=
