language: node_js
node_js:
- '4'
notifications:
  email: false
branches:
  except:
  - gh-pages
after_success:
- if [ $TRAVIS_TAG ]; then make deploy; fi
env:
  global:
    secure: dKwgL1rXYZXWAG6DPvrgr5Fvt2L9veYYDk7CoHRUBx5z8pcaPsklczmqM5Fb250KSnpPjaNyeLkxpwiZ205hkxe7yEbuAjdsRiuMhnOWCPa00lpch4h1tdOEPvyXE7YeZRLBOELUcEXSSmpIrvFFdt4kBUK93owjKReGjwh9G0ObtLwrBMULiaTDMSFi9S1si8eGR0OcxcX6dEAzZL88+hNptSNLkhXemDj/uUW2/cWLm8HGtJL40AtmseXmpylEeDxsTq/Q+dbfNxZ+RRHNUjziWMUgzAvJMl8Ty4xfcYp1pibx1MNSi8+L8+8cZjIutM+LDbvW6b2VVaI9/1BV16XC/v0UZMwGMOqMsp890sGTJEnk/lsFqhL94uJj4isYx9n/L5/UvWWSWA8E8JRnAosoAyuEVDwNILl+7f9sTZijgB6M4GfWIrQgp0sgY5lUMo9ES5wypPAXKydv5OcW8aPl0zbU5RedmG+VfvgntVXq92IsaBtn4vhoj0KMzcxu/QAUPWoEY2zY9EZxVV2N7YN7/Pb9HRV6SXdAyK2s7cjMn0qdmp4ukQDJCegtwRQp72JlAMdX3aSZCV+AtitHweXvOYXsokcSkr543fi2zulQ2UaUDBuLiKsrP/R4PqPb7j6ilNZ2rg+BNJLLxNwTfbGAuqHFmV2D66SUnrIJvWg=
